// This file is part of OpenMVG, an Open Multiple View Geometry C++ library.

// Copyright (c) 2015 Pierre MOULON.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#ifndef OPENMVG_MATCHING_CASCADE_HASHER_HPP
#define OPENMVG_MATCHING_CASCADE_HASHER_HPP

//------------------
//-- Bibliography --
//------------------
//- [1] "Fast and Accurate Image Matching with Cascade Hashing for 3D Reconstruction"
//- Authors: Jian Cheng, Cong Leng, Jiaxiang Wu, Hainan Cui, Hanqing Lu.
//- Date: 2014.
//- Conference: CVPR.
//
// This implementation is based on the Theia library implementation.
//
// Update compare to the initial paper [1] and initial author code:
// - hashing projection is made by using Eigen to use vectorization (Theia)
// - replace the BoxMuller random number generation by C++ 11 random number generation (OpenMVG)
// - this implementation can support various descriptor length and internal type (OpenMVG)
// -  SIFT, SURF, ... all scalar based descriptor
//

// Copyright (C) 2014 The Regents of the University of California (Regents).
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//
//     * Redistributions in binary form must reproduce the above
//       copyright notice, this list of conditions and the following
//       disclaimer in the documentation and/or other materials provided
//       with the distribution.
//
//     * Neither the name of The Regents or University of California nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// Please contact the author of this library if you have any questions.
// Author: Chris Sweeney (cmsweeney@cs.ucsb.edu)


#include <cmath>
#include <random>
#include <utility>
#include <vector>

#include "openMVG/matching/indMatch.hpp"
#include "openMVG/matching/metric.hpp"
#include "openMVG/numeric/eigen_alias_definition.hpp"
#include "openMVG/stl/dynamic_bitset.hpp"

namespace openMVG {
namespace matching {

struct HashedDescription {
  // Hash code generated by the primary hashing function.
  stl::dynamic_bitset hash_code;

  // Each bucket_ids[x] = y means the descriptor belongs to bucket y in bucket
  // group x.
  std::vector<uint16_t> bucket_ids;
};

struct HashedDescriptions{
  // Flat contiguous hash codes for cache-friendly matching.
  // flat_hash_codes[i*2] = low 64 bits, flat_hash_codes[i*2+1] = high 64 bits.
  std::vector<uint64_t> flat_hash_codes;

  // Flat contiguous bucket ids.
  // flat_bucket_ids[i * nb_bucket_groups + g] = bucket for desc i, group g.
  std::vector<uint16_t> flat_bucket_ids;
  int nb_bucket_groups = 0;
  int num_descriptors = 0;

  using Bucket = std::vector<int>;
  // buckets[bucket_group][bucket_id] = bucket (container of description ids).
  std::vector<std::vector<Bucket>> buckets;
};

// This hasher will hash descriptors with a two-step hashing system:
// 1. it generates a hash code,
// 2. it determines which buckets the descriptors belong to.
// Retrieval step is fast since:
// - only descriptors in the same bucket are likely to be good matches.
//   - 1. a hamming distance is used for fast neighbor candidate retrieval
//   - 2. the L2 distance is computed only a reduced selection of approximate neighbor
//
// Implementation is based on the paper [1].
// If you use this matcher, please cite the paper.
class CascadeHasher {
private:

  // The number of bucket bits.
  int nb_bits_per_bucket_;
  // The number of dimensions of the Hash code.
  int nb_hash_code_;
  // The number of bucket groups.
  int nb_bucket_groups_;
  // The number of buckets in each group.
  int nb_buckets_per_group_;

public:
  CascadeHasher() = default;

  // Creates the hashing projections (cascade of two level of hash codes)
  bool Init
  (
    const uint8_t nb_hash_code = 128,
    const uint8_t nb_bucket_groups = 6,
    const uint8_t nb_bits_per_bucket = 10,
    const unsigned random_seed = std::mt19937::default_seed)
  {
    nb_bucket_groups_= nb_bucket_groups;
    nb_hash_code_ = nb_hash_code;
    nb_bits_per_bucket_ = nb_bits_per_bucket;
    nb_buckets_per_group_= 1 << nb_bits_per_bucket;

    //
    // Box Muller transform is used in the original paper to get fast random number
    // from a normal distribution with <mean = 0> and <variance = 1>.
    // Here we use C++11 normal distribution random number generator
    std::mt19937 gen(random_seed);
    std::normal_distribution<> d(0,1);

    primary_hash_projection_.resize(nb_hash_code, nb_hash_code);

    // Initialize primary hash projection.
    for (int i = 0; i < nb_hash_code; ++i)
    {
      for (int j = 0; j < nb_hash_code; ++j)
        primary_hash_projection_(i, j) = d(gen);
    }

    // Initialize secondary hash projection.
    secondary_hash_projection_.resize(nb_bucket_groups);
    for (int i = 0; i < nb_bucket_groups; ++i)
    {
      secondary_hash_projection_[i].resize(nb_bits_per_bucket_,
        nb_hash_code);
      for (int j = 0; j < nb_bits_per_bucket_; ++j)
      {
        for (int k = 0; k < nb_hash_code; ++k)
          secondary_hash_projection_[i](j, k) = d(gen);
      }
    }
    return true;
  }

  template <typename MatrixT>
  static Eigen::VectorXf GetZeroMeanDescriptor
  (
    const MatrixT & descriptions
  )
  {
    if (descriptions.rows() == 0) {
      return {};
    }
    // Compute the ZeroMean descriptor
    return descriptions.template cast<float>().colwise().mean();
  }


  template <typename MatrixT>
  HashedDescriptions CreateHashedDescriptions
  (
    const MatrixT & descriptions,
    const Eigen::VectorXf & zero_mean_descriptor
  ) const
  {
    HashedDescriptions hd;
    if (descriptions.rows() == 0) {
      return hd;
    }

    const int nbDesc = static_cast<int>(descriptions.rows());
    hd.num_descriptors = nbDesc;
    hd.nb_bucket_groups = nb_bucket_groups_;
    hd.flat_hash_codes.resize(nbDesc * 2, 0);
    hd.flat_bucket_ids.resize(nbDesc * nb_bucket_groups_);

    Eigen::VectorXf descriptor(descriptions.cols());
    for (int i = 0; i < nbDesc; ++i)
    {
      descriptor = descriptions.row(i).template cast<float>();
      descriptor -= zero_mean_descriptor;

      // Primary hash -> flat uint64_t pair
      const Eigen::VectorXf primary_projection = primary_hash_projection_ * descriptor;
      uint64_t lo = 0, hi = 0;
      for (int j = 0; j < nb_hash_code_ && j < 64; ++j)
        if (primary_projection(j) > 0)
          lo |= (uint64_t(1) << j);
      for (int j = 64; j < nb_hash_code_; ++j)
        if (primary_projection(j) > 0)
          hi |= (uint64_t(1) << (j - 64));
      hd.flat_hash_codes[i * 2]     = lo;
      hd.flat_hash_codes[i * 2 + 1] = hi;

      // Secondary hash -< flat bucket ids
      Eigen::VectorXf secondary_projection;
      for (int j = 0; j < nb_bucket_groups_; ++j)
      {
        uint16_t bucket_id = 0;
        secondary_projection = secondary_hash_projection_[j] * descriptor;
        for (int k = 0; k < nb_bits_per_bucket_; ++k)
          bucket_id = (bucket_id << 1) + (secondary_projection(k) > 0 ? 1 : 0);
        hd.flat_bucket_ids[i * nb_bucket_groups_ + j] = bucket_id;
      }
    }

    // Build the Buckets
    hd.buckets.resize(nb_bucket_groups_);
    for (int i = 0; i < nb_bucket_groups_; ++i)
    {
      hd.buckets[i].resize(nb_buckets_per_group_);
      for (int j = 0; j < nbDesc; ++j)
      {
        const uint16_t bid = hd.flat_bucket_ids[j * nb_bucket_groups_ + i];
        hd.buckets[i][bid].push_back(j);
      }
    }
    return hd;
  }

  // Matches two collection of hashed descriptions with a fast matching scheme
  // based on the hash codes previously generated.
  template <typename MatrixT, typename DistanceType>
  void Match_HashedDescriptions
  (
    const HashedDescriptions& hashed_descriptions1,
    const MatrixT & descriptions1,
    const HashedDescriptions& hashed_descriptions2,
    const MatrixT & descriptions2,
    IndMatches * pvec_indices,
    std::vector<DistanceType> * pvec_distances,
    const int NN = 2
  ) const
  {
    using MetricT = L2<typename MatrixT::Scalar>;
    MetricT metric;

    static const int kNumTopCandidates = 10;

    const int numDesc2 = hashed_descriptions2.num_descriptors;
    std::vector<int> candidate_descriptors;
    candidate_descriptors.reserve(numDesc2);
    Eigen::MatrixXi candidate_hamming_distances(numDesc2, nb_hash_code_ + 1);
    Eigen::VectorXi num_descriptors_with_hamming_distance(nb_hash_code_ + 1);
    std::vector<std::pair<DistanceType, int>> candidate_euclidean_distances;
    candidate_euclidean_distances.reserve(kNumTopCandidates);
    std::vector<char> used_descriptor(numDesc2, 0);

    const uint64_t* __restrict flat1 = hashed_descriptions1.flat_hash_codes.data();
    const uint64_t* __restrict flat2 = hashed_descriptions2.flat_hash_codes.data();
    const uint16_t* __restrict bucketIds1 = hashed_descriptions1.flat_bucket_ids.data();
    const int nbg = nb_bucket_groups_;

    for (int i = 0; i < hashed_descriptions1.num_descriptors; ++i)
    {
      candidate_descriptors.clear();
      num_descriptors_with_hamming_distance.setZero();
      candidate_euclidean_distances.clear();

      const uint16_t* qBuckets = bucketIds1 + i * nbg;
      for (int j = 0; j < nbg; ++j)
      {
        const uint16_t bucket_id = qBuckets[j];
        for (const auto& feature_id : hashed_descriptions2.buckets[j][bucket_id])
        {
          candidate_descriptors.emplace_back(feature_id);
          used_descriptor[feature_id] = 0;
        }
      }

      if (candidate_descriptors.size() <= NN)
        continue;

      const uint64_t q_lo = flat1[i * 2];
      const uint64_t q_hi = flat1[i * 2 + 1];

      for (const int candidate_id : candidate_descriptors)
      {
        if (!used_descriptor[candidate_id])
        {
          used_descriptor[candidate_id] = 1;
          const uint64_t c_lo = flat2[candidate_id * 2];
          const uint64_t c_hi = flat2[candidate_id * 2 + 1];
#ifdef _MSC_VER
          const unsigned int hamming_distance =
            static_cast<unsigned int>(__popcnt64(q_lo ^ c_lo)) +
            static_cast<unsigned int>(__popcnt64(q_hi ^ c_hi));
#else
          const unsigned int hamming_distance =
            static_cast<unsigned int>(__builtin_popcountll(q_lo ^ c_lo)) +
            static_cast<unsigned int>(__builtin_popcountll(q_hi ^ c_hi));
#endif
          candidate_hamming_distances(
              num_descriptors_with_hamming_distance(hamming_distance)++,
              hamming_distance) = candidate_id;
        }
      }

      candidate_euclidean_distances.reserve(kNumTopCandidates);
      for (int j = 0; j < candidate_hamming_distances.cols() &&
        (candidate_euclidean_distances.size() < kNumTopCandidates); ++j)
      {
        for (int k = 0; k < num_descriptors_with_hamming_distance(j) &&
          (candidate_euclidean_distances.size() < kNumTopCandidates); ++k)
        {
          const int candidate_id = candidate_hamming_distances(k, j);
          const DistanceType distance = metric(
            descriptions2.row(candidate_id).data(),
            descriptions1.row(i).data(),
            descriptions1.cols());
          candidate_euclidean_distances.emplace_back(distance, candidate_id);
        }
      }

      if (candidate_euclidean_distances.size() >= NN)
      {
        std::partial_sort(candidate_euclidean_distances.begin(),
          candidate_euclidean_distances.begin() + NN,
          candidate_euclidean_distances.end());
        for (int l = 0; l < NN; ++l)
        {
          pvec_distances->emplace_back(candidate_euclidean_distances[l].first);
          pvec_indices->emplace_back(IndMatch(i,candidate_euclidean_distances[l].second));
        }
      }
    }
  }

  // Overload accepting pre-allocated scratch buffers.
  template <typename MatrixT, typename DistanceType>
  void Match_HashedDescriptions
  (
    const HashedDescriptions& hashed_descriptions1,
    const MatrixT & descriptions1,
    const HashedDescriptions& hashed_descriptions2,
    const MatrixT & descriptions2,
    IndMatches * pvec_indices,
    std::vector<DistanceType> * pvec_distances,
    const int NN,
    std::vector<int> & candidate_descriptors,
    std::vector<std::pair<DistanceType, int>> & candidate_euclidean_distances,
    std::vector<char> & used_descriptor
  ) const
  {
    using MetricT = L2<typename MatrixT::Scalar>;
    MetricT metric;

    static const int kNumTopCandidates = 10;

    const int numDesc2 = hashed_descriptions2.num_descriptors;

    if (static_cast<int>(used_descriptor.size()) < numDesc2)
    {
      used_descriptor.resize(numDesc2);
    }

    const uint64_t* __restrict flat1 = hashed_descriptions1.flat_hash_codes.data();
    const uint64_t* __restrict flat2 = hashed_descriptions2.flat_hash_codes.data();
    const uint16_t* __restrict bucketIds1 = hashed_descriptions1.flat_bucket_ids.data();
    const int nbg = nb_bucket_groups_;

    // Per-query top-K hamming candidates — replaces the 3.3 MB Eigen matrix
    struct HammingCandidate {
      unsigned int distance;
      int id;
      bool operator<(const HammingCandidate& o) const { return distance < o.distance; }
    };
    HammingCandidate top_hamming[kNumTopCandidates];

    for (int i = 0; i < hashed_descriptions1.num_descriptors; ++i)
    {
      candidate_descriptors.clear();
      candidate_euclidean_distances.clear();

      const uint16_t* qBuckets = bucketIds1 + i * nbg;
      for (int j = 0; j < nbg; ++j)
      {
        const uint16_t bucket_id = qBuckets[j];
        for (const auto& feature_id : hashed_descriptions2.buckets[j][bucket_id])
        {
          candidate_descriptors.emplace_back(feature_id);
          used_descriptor[feature_id] = 0;
        }
      }

      if (candidate_descriptors.size() <= NN)
        continue;

      const uint64_t q_lo = flat1[i * 2];
      const uint64_t q_hi = flat1[i * 2 + 1];

      int n_top = 0;
      unsigned int worst_hamming = std::numeric_limits<unsigned int>::max();

      for (const int candidate_id : candidate_descriptors)
      {
        if (!used_descriptor[candidate_id])
        {
          used_descriptor[candidate_id] = 1;

          const uint64_t c_lo = flat2[candidate_id * 2];
          const uint64_t c_hi = flat2[candidate_id * 2 + 1];
#ifdef _MSC_VER
          const unsigned int hamming_distance =
            static_cast<unsigned int>(__popcnt64(q_lo ^ c_lo)) +
            static_cast<unsigned int>(__popcnt64(q_hi ^ c_hi));
#else
          const unsigned int hamming_distance =
            static_cast<unsigned int>(__builtin_popcountll(q_lo ^ c_lo)) +
            static_cast<unsigned int>(__builtin_popcountll(q_hi ^ c_hi));
#endif
          if (n_top < kNumTopCandidates)
          {
            top_hamming[n_top++] = {hamming_distance, candidate_id};
            if (n_top == kNumTopCandidates)
            {
              // Build initial heap so worst is at top_hamming[0]
              std::make_heap(top_hamming, top_hamming + kNumTopCandidates);
              worst_hamming = top_hamming[0].distance;
            }
          }
          else if (hamming_distance < worst_hamming)
          {
            // Replace worst
            std::pop_heap(top_hamming, top_hamming + kNumTopCandidates);
            top_hamming[kNumTopCandidates - 1] = {hamming_distance, candidate_id};
            std::push_heap(top_hamming, top_hamming + kNumTopCandidates);
            worst_hamming = top_hamming[0].distance;
          }
        }
      }

      // Compute L2 on the top hamming candidates
      candidate_euclidean_distances.reserve(kNumTopCandidates);
      for (int j = 0; j < n_top; ++j)
      {
        const int candidate_id = top_hamming[j].id;
        const DistanceType distance = metric(
          descriptions2.row(candidate_id).data(),
          descriptions1.row(i).data(),
          descriptions1.cols());
        candidate_euclidean_distances.emplace_back(distance, candidate_id);
      }

      if (candidate_euclidean_distances.size() >= NN)
      {
        std::partial_sort(candidate_euclidean_distances.begin(),
          candidate_euclidean_distances.begin() + NN,
          candidate_euclidean_distances.end());
        for (int l = 0; l < NN; ++l)
        {
          pvec_distances->emplace_back(candidate_euclidean_distances[l].first);
          pvec_indices->emplace_back(IndMatch(i, candidate_euclidean_distances[l].second));
        }
      }
    }
  }

  private:
  // Primary hashing function.
  Eigen::MatrixXf primary_hash_projection_;

  // Secondary hashing function.
  std::vector<Eigen::MatrixXf> secondary_hash_projection_;
};

}  // namespace matching
}  // namespace openMVG

#endif // OPENMVG_MATCHING_CASCADE_HASHER_HPP
